
# PyMOL Presentation Script for Project Acridine
# Generated by AI Lab Assistant

reinitialize
bg_color white

# Load the Receptor (Target)
load Target_TopoII_Receptor.pdb, receptor
hide everything, receptor
show cartoon, receptor
color gray80, receptor
set transparency, 0.4, receptor

# Load the Candidate (Drug)
load Candidate_Alpha_79.sdf, candidate
show sticks, candidate
# Color by element (Carbon=Green for 'Good Match')
color green, (name C*)
color red, (name O*)
color blue, (name N*)
util.cnc candidate

# Highlight the "Key Feature" (The Amino-Ethyl Tail)
select tail_region, candidate and (element N or element O)
show spheres, tail_region
set sphere_scale, 0.3, tail_region

# View Setup
zoom candidate, 10
set ray_shadows, 0
set orthoscopic, on
